# Generated by Django 5.0 on 2023-12-10 18:36

import app.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('contributors', models.ManyToManyField(limit_choices_to={'groups__name__in': ['Developpers', 'Clients']}, to=settings.AUTH_USER_MODEL)),
                ('status', models.ManyToManyField(to='app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('estimation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('passed_time', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('type', models.CharField(choices=[('master', 'master'), ('normal', 'noraml')], max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('contributor', models.ForeignKey(limit_choices_to={'groups__name__in': ['Developpers', 'Clients']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 12, 10, 19, 36, 40, 976458), editable=False)),
                ('contributor', models.ForeignKey(limit_choices_to={'groups__name__in': ['Developpers', 'Clients']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.TextField(max_length=2000)),
                ('time', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, validators=[app.models.Track.no_future])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ticket')),
                ('user', models.ForeignKey(limit_choices_to={'groups__name__in': ['Developpers']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
