# Generated by Django 5.0 on 2023-12-10 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 19, 43, 32, 343193), editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passed_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
