# Generated by Django 5.0 on 2023-12-09 14:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_status_options_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
