# Generated by Django 5.0 on 2023-12-10 18:44

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comment_date_alter_ticket_passed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 19, 44, 13, 457508), editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
