# Generated by Django 5.0 on 2023-12-10 14:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 12, 10, 14, 12, 15, 95006, tzinfo=datetime.timezone.utc))]),
        ),
    ]
