# Generated by Django 5.0 on 2023-12-10 14:24

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 15, 24, 50, 483518), validators=[app.models.Comment.no_future]),
        ),
    ]
