# Generated by Django 5.0 on 2023-12-10 14:36

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 15, 36, 36, 129361), validators=[app.models.Comment.no_future]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estimation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passed_time',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
