# Generated by Django 5.0 on 2023-12-10 15:42

import app.models
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_comment_date_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 16, 42, 27, 955634), validators=[app.models.Comment.no_future]),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('hold..', 'hold..'), ('dev..', 'dev..'), ('préproduction..', 'préproduction..'), ('prod..', 'prod..'), ('completed', 'completed')], default='hold..', max_length=20),
        ),
    ]
