# Generated by Django 5.0 on 2023-12-10 15:47

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_comment_date_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 16, 47, 16, 642231), validators=[app.models.Comment.no_future]),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Wait', 'Wait'), ('Dev..', 'Dev..'), ('Préproduction..', 'Préproduction..'), ('production..', 'production..'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
    ]
