# Generated by Django 5.0 on 2023-12-10 15:48

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_comment_date_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 16, 48, 23, 314273), validators=[app.models.Comment.no_future]),
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ManyToManyField(to='app.status'),
        ),
    ]
